In [2]:
!pip install numpy

In [3]:
import numpy as np

*****************
Arrays
*****************

In [4]:
arr=np.array([[1,2,3],
              [4,5,6]])

print("Array is of type:",type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array:",arr.size)
print("Array stores element of type:",arr.dtype)


Array is of type: <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array: 6
Array stores element of type: int64


*****************
Array Creation
*****************

In [5]:
#creating numpy array  from list  with type float
a=np.array([[1,2,4],[5,8,7]], dtype="float")
print("Array created using passed list:\n",a)

#creating array from tuple
b=np.array((1,3,2))
print("\nAn array created using passed tuple:\n",b)

#creating a 3*4 array with all zeros
c=np.zeros((3,4))
print("\nAn array initialized with all zeros:\n", c)

#constant value array of complex type
d=np.full((3,3),6,dtype='complex')
print("\nAn array initialized with all 6s.Array type is complex:\n",d)

#create an array with random values
e=np.random.random((2,2))
print("\nA random array:\n", e)

#create a sequence of integer from 0 to 30 with steps of 5
f=np.arange(0,30,5)
print("\nA sequential array with steps of 5:\n",f)

#create a sequence of 10 values in range 0 to 5
g=np.linspace(0,5,10)
print("\nA sequential array with 10 values between 0 and 5:\n",g)

# reshaping 3X4 array to 2X2X3 array
arr=np.array([[1,2,3,4],
              [5,2,3,6],
              [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print("\nOriginal array:\n",arr)
print("\nReshaped array:\n",newarr)


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

An array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.58443796 0.30815725]
 [0.49972472 0.0751254 ]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 3 6]
 [1 2 0 1]]

Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[3 6 1]
  [2 0 1]]]


In [18]:
#fDocumentation
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

*****************
Array Indexing
*****************

In [6]:
arr=np.array([[-1,2,0,4],
              [4,-0.5,6,0],
              [2.6,0,7,8],
              [3,-7,4,2.0]])

print("\nArray:\n",arr)
print("Array from 2nd row to 3rd col:\n",arr[1:,:3])
print("Array with skipping columns in size 2:\n",arr[1:,:3:2])
#print("\nskipping rows and cols in size 2:\n",arr[1::2, :3:2])



Array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array from 2nd row to 3rd col:
 [[ 4.  -0.5  6. ]
 [ 2.6  0.   7. ]
 [ 3.  -7.   4. ]]
Array with skipping columns in size 2:
 [[4.  6. ]
 [2.6 7. ]
 [3.  4. ]]


In [7]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print("\nArray:\n",arr)
#slicing
temp=arr[:2,::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

#integer array indexing example
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3,0):\n",temp)

#boolean array indexing example
cond=arr>0
temp=arr[cond]
print("\nElements greater than 0:\n",temp)


Array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


*****************
Basic Operation
*****************

In [9]:
#Operations on single array -for more refer note|
a=np.array([1,2,5,3])
print("Adding 1 to every element:",a+1)
print("Subtracting 3 from every element:",a-3)
print("Multiplying each element by 10:",a*10)
print("Squaring each element:", a**2)
a *= 2
print("Doubled each element of original array:", a)

# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from every element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


*****************
Sorting array
*****************

In [11]:
a = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])

# sorted array
print("Array elements in sorted order:\n", np.sort(a, axis = None))

# sort array row-wise
print("Row-wise sorted array:\n", np.sort(a, axis = 1))

# specify sort algorithm
print("Column wise sort by applying merge-sort:\n", np.sort(a, axis = 0, kind = 'mergesort'))

# example to show sorting of structured array
## set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
## values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
## creating array
arr = np.array(values, dtype = dtypes)
print("\nArray sorted by names:\n", np.sort(arr, order = 'name'))
print("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


*****************
Stacking and Splitting
*****************

In [13]:
a=np.array([[1,2],
           [3,4]])

b=np.array([[5,6],
           [7,8]])

print("Vertical stacking:\n",np.vstack((a,b)))
print("\nHorizantal stacking:\n",np.hstack((a,b)))

c=[5,6]
# stacking columns
print("\nColumn stacking:\n",np.column_stack((a,c)))
#concatenation method
print("\nConcatenating to 2nd axis:\n",np.concatenate((a,b),1))


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizantal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [14]:
#Splitting
a=np.array([[1,3,5,7,9,11],
            [2,4,6,8,10,12]])
# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n",np.hsplit(a,2))

# vertical splitting
print("Splitting along vertical axis into 2 parts:\n",np.vsplit(a,2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]
